
project_id = "kdpqimetajnhcqseajok"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "https://kdpqimetajnhcqseajok.supabase.co"

[functions.create-admin-user]
verify_jwt = false

[functions.create-tenant-account]
verify_jwt = false

[functions.create-user-with-role]
verify_jwt = true

[functions.get-sms-provider]
verify_jwt = true

[functions.send-maintenance-notification]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.trial-manager]
verify_jwt = false

[functions.create-billing-checkout]
verify_jwt = true

[functions.confirm-billing-upgrade]
verify_jwt = true

[functions.generate-service-invoice]
verify_jwt = false

[functions.automated-monthly-billing]
verify_jwt = false

[functions.activate-commission-plan]
verify_jwt = true

[functions.telemetry-heartbeat]
verify_jwt = false

[functions.telemetry-events]
verify_jwt = false

[functions.telemetry-errors]
verify_jwt = false
