// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://kdpqimetajnhcqseajok.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcHFpbWV0YWpuaGNxc2Vham9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDQxMTAsImV4cCI6MjA2OTU4MDExMH0.VkqXvocYAYO6RQeDaFv8wVrq2xoKKfQ8UVj41az7ZSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Enhance functions.invoke with reliable routing to avoid FunctionsFetchError
try {
  const originalInvoke = (supabase.functions as any).invoke.bind(supabase.functions);
  (supabase.functions as any).invoke = async (name: string, options?: any) => {
    const body = options?.body ?? {};

    // Prepare headers: prefer caller headers; add user JWT if available; fallback to anon; add origin
    const extraHeaders: Record<string, string> = { ...(options?.headers || {}) };
    try {
      const { data: sessionData } = await supabase.auth.getSession();
      const access = sessionData?.session?.access_token;
      if (access) {
        extraHeaders['Authorization'] = `Bearer ${access}`;
      } else if (body?.force || name === 'create-tenant-account' || name === 'create-user-with-role') {
        extraHeaders['x-force-create'] = 'true';
      }
    } catch {}
    if (typeof window !== 'undefined' && !extraHeaders['origin']) extraHeaders['origin'] = window.location.origin;

    // 1) Try server proxy first (uses service role on server)
    let proxyFailedDetails: any = null;
    try {
      const res = await fetch(`/api/edge/${name}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...extraHeaders },
        body: JSON.stringify(body)
      });
      const text = await res.text();
      let data: any; try { data = JSON.parse(text); } catch { data = text; }
      if (res.ok) return { data, error: null } as any;
      proxyFailedDetails = { status: res.status, details: data };
    } catch (fallbackErr: any) {
      proxyFailedDetails = fallbackErr?.message || String(fallbackErr);
    }

    // 2) Direct call to Supabase Edge Function
    try {
      const fnUrl = `${SUPABASE_URL.replace(/\/$/, '')}/functions/v1/${name}`;
      const res = await fetch(fnUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_PUBLISHABLE_KEY,
          'Authorization': extraHeaders['Authorization'] || `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
          ...extraHeaders,
        },
        body: JSON.stringify(body)
      });
      const text = await res.text();
      let data: any; try { data = JSON.parse(text); } catch { data = text; }
      if (res.ok) return { data, error: null } as any;
      // If direct fetch says unauthorized and we had a JWT, keep details
      const directFailedDetails = { status: res.status, details: data };

      // 3) As a last resort, call original invoke (may throw FunctionsFetchError)
      try {
        const result = await originalInvoke(name, options);
        if (result?.error) throw result.error;
        return result;
      } catch (err: any) {
        const parts: string[] = [];
        if (err?.message) parts.push(err.message);
        if (proxyFailedDetails) parts.push(`proxy: ${typeof proxyFailedDetails === 'string' ? proxyFailedDetails : JSON.stringify(proxyFailedDetails)}`);
        parts.push(`direct: ${JSON.stringify(directFailedDetails)}`);
        return { data: null as any, error: { message: parts.join(' | ') } };
      }
    } catch (directErr: any) {
      // 3) Original invoke if even fetch failed to construct
      try {
        const result = await originalInvoke(name, options);
        if (result?.error) throw result.error;
        return result;
      } catch (err: any) {
        const parts: string[] = [];
        if (err?.message) parts.push(err.message);
        if (directErr?.message) parts.push(`direct: ${directErr.message}`);
        if (proxyFailedDetails) parts.push(`proxy: ${typeof proxyFailedDetails === 'string' ? proxyFailedDetails : JSON.stringify(proxyFailedDetails)}`);
        return { data: null as any, error: { message: parts.join(' | ') } };
      }
    }
  };
} catch {}
